{
"sites":[
//{"key": "T4a","name": " T4聚合","type": 4,"api": "https://t4.secan.icu/vod?sites=all&ali_token=4acb3ad2f2254ba1b566279f7cd98ba3&timeout=5","searchable": 1,"quickSearch": 1,"filterable": 1},
 //==================================pluto.js版======================================================================================================================================================================================================
{
"key" : "drpy_js_素白白",
"name" : "看素白白┃国内外剧",
"type" : 3,
"api" : "https://gitee.com/qizhen169xt/cool_white/raw/master/videos-tool/lib/drpy.min.js",
"ext" : "https://gitee.com/qizhen169xt/cool_white/raw/master/videos-tool/js/%E7%B4%A0%E7%99%BD%E7%99%BD.js"
},
{"key":"csp_Sp_酷云七七","name":"爬虫┃酷云七七","type":3,"api":"csp_Kunyu77"  ,"searchable":1,"quickSearch":1,"filterable":1},		
{"key":"csp_Sp_图图影视","name":"爬虫┃图图影视","type":3,"api":"csp_AppTT"    ,"playerType":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Sp_新视觉","name":"爬虫┃新视觉","type":3,"api":"csp_Xinsj"    ,"playerType":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Sp_轻松视频","name":"爬虫┃轻松视频","type":3,"api":"csp_RelaxSP"  ,"searchable":1,"quickSearch":1,"filterable":1,"playerType":2"},
{"key":"csp_Sp_蓝光影视","name":"爬虫┃蓝光影视","type":3,"api":"csp_Lgyy"     ,"searchable":1,"quickSearch":1,"filterable":1,"jar":"","ext":""},
{"key":"csp_Sp_农民影视","name":"爬虫┃农民影视","type":3,"api":"csp_Nmys"     ,"searchable":1,"quickSearch":1,"filterable":1"},
{"key":"csp_Sp_迷你影视","name":"爬虫┃迷你影视","api":"csp_MiniYs"            ,"type":3,"filterable":1,"quickSearch":1,"searchable":1"},
{"key":"csp_Sp_棉花影视","name":"爬虫┃棉花影视","type":3,"api":"csp_MianHua"  ,"searchable":1,"quickSearch":1,"filterable":0"},
{"key":"csp_Sp_石榴电影","name":"爬虫┃石榴电影","api":"csp_ShiLiuDY"          ,"type":3,"filterable":1,"quickSearch":1,"playerType":2,"searchable":1"},
{"key":"csp_Sp_小苹果源","name":"爬虫┃小苹果源","type":3,"api":"csp_LiteApple","searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Sp_低端影视","name":"爬虫┃低端影视","type":3,"api":"csp_Ddrk"     ,"click": "ddys.tv;#vjsp > button","searchable":1,"quickSearch":1,"filterable":0},
{"key":"csp_Sp_利奥影视","name":"爬虫┃利奥影视","type":3,"api":"csp_Lib"      ,"searchable":1,"quickSearch":1,"filterable":0},
{"key":"csp_Sp_焦炭影视","name":"爬虫┃焦炭影视","type":3,"api":"csp_Cokemv"   ,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Sp_厂长影视","name":"爬虫┃厂长资源","type":3,"api":"csp_Czsapp"   ,"searchable":1,"quickSearch":1,"filterable":0"},
{"key":"csp_Sp_饭团影视","name":"爬虫┃饭团影视","type":3,"api":"csp_Fantuan"  ,"searchable":1,"quickSearch":1,"filterable":1,"ext":""},
{"key":"csp_Sp_快看影视","name":"爬虫┃快看影视","type":3,"api":"csp_Kuaikan"  ,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Sp_追剧达人","name":"爬虫┃追剧达人","type":3,"api":"csp_Zjdr"     ,"searchable":1,"quickSearch":1,"filterable":1,"jar":"","ext":""},
{"key":"csp_Sp_爱看影视","name":"爬虫┃爱看影视","type":3,"api":"csp_IKan"     ,"searchable":1,"quickSearch":1,"filterable":1"},
{"key":"csp_Sp_奥特影视","name":"爬虫┃奥特影视","type":3,"api":"csp_Auete"    ,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Sp_视界影视","name":"爬虫┃视界影视","type":3,"api":"csp_KanSJ"    ,"filterable":1,"quickSearch":1,"searchable":1"},
{"key":"csp_Sp_三亿影视","name":"爬虫┃三亿影视","type":3,"api":"csp_EEEDY"    ,"searchable":1,"quickSearch":1,"filterable":1}, 
{"key":"csp_Sp_三五电影","name":"爬虫┃三五电影","type":3,"api":"csp_Dy555"    ,"filterable":1,"quickSearch":1,"searchable":1},
{"key":"csp_Sp_两个磁力","name":"爬虫┃两个磁力","type":3,"api":"csp_Bttoo"    ,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Sp_乐猪影视","name":"爬虫┃乐猪影视","type":3,"api":"csp_Lezhu"    ,"filterable":1,"quickSearch":1,"searchable":1}, 
{"key":"csp_Sp_影视工厂","name":"爬虫┃影视工厂","type":3,"api":"csp_Ysgc"     ,"searchable":1,"quickSearch":1,"filterable":0,"ext":""},
{"key":"csp_Sp_可乐影视","name":"爬虫┃可乐影视","type":3,"api":"csp_Cokemv"   ,"playerType":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Sp_听书故事","name":"听书┃主人听书","type":3,"api":"csp_Tbook"    ,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Sp_天天影视","name":"爬虫┃天天影视","type":"3","api":"csp_Dora"   ,"searchable":"1","quickSearch":"1","filterable":"1","ext":"","jar":""},
{"key":"csp_Sp_鸭奈飞源","name":"爬虫┃鸭奈飞源","type":"3","api":"csp_Dora"   ,"searchable":"1","quickSearch":"1","filterable":"1","ext":"","jar":""},
{"key":"csp_Sp_胖虎影视","name":"爬虫┃胖虎影视","type":"3","api":"csp_Dora"   ,"searchable":"1","quickSearch":"1","filterable":"1","ext":"","jar":""},
{"key":"csp_Sp_哔滴影视","name":"爬虫┃哔滴影视","type":3,"api":"csp_Bdys01"   ,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Sp_在线之家","name":"爬虫┃在线之家","type":3,"api":"csp_Zxzj"     ,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Sp_追剧喵源","name":"爬虫┃追剧喵源","type":3,"api":"csp_ZJMiao"   ,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Sp_神马影视","name":"爬虫┃神马影视","type":3,"api":"csp_Smdyy"    ,"filterable":1,"quickSearch":1,"searchable":1},
{"key":"csp_Sp_动漫巴士","name":"动漫┃动漫巴士","type":3,"api":"csp_Dm84"     ,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Sp_齐齐动漫","name":"动漫┃齐齐动漫","api":"csp_DM77"              ,"type":3,"filterable":1,"quickSearch":1,"searchable":1,"ext":""},
{"key":"csp_Sp_弹幕动漫","name":"动漫┃弹幕动漫","type":3,"api":"csp_Anfuns"   ,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Sp_唐人街源","name":"境外┃唐人街源","type":3,"api":"csp_Tangrenjie","searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Sp_泥巴影视","name":"境外┃泥巴影视","type":3,"api":"csp_Nbys"     ,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Sp_双十影视","name":"爬虫┃双十影视","type":3,"api":"csp_Dy1010"   ,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Sp_壹零壹源","name":"爬虫┃壹零壹源","type":3,"api":"csp_If101"    ,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Sp_念影影视","name":"爬虫┃念影影视","type":3,"api":"csp_Nianying" ,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Sp_天空影视","name":"爬虫┃天空影视","type":3,"api":"csp_Tkys"     ,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Sp_南柯影视","name":"爬虫┃南柯影视","type":3,"api":"csp_Nkdy"     ,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Sp_小熊影视","name":"爬虫┃小熊影视","type":3,"api":"csp_Xxys"     ,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Sp_小宝影视","name":"爬虫┃小宝影视","type":3,"api":"csp_Xiaoh"    ,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Sp_完美看看","name":"爬虫┃完美看看","api":"csp_Wmkk"              ,"type":3,"filterable":1,"quickSearch":1,"searchable":1},
{"key":"csp_Sp_乐橙视频","name":"爬虫┃乐橙视频","api":"csp_LvChaYs"           ,"type":3,"filterable":1,"quickSearch":1,"searchable":1,"ext":""},
{"key":"csp_Sp_剧荒影院","name":"爬虫┃剧荒影院","type":3,"api":"csp_Juhuang"  ,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Sp_樱花动漫","name":"爬虫┃樱花动漫","type":3,"api":"csp_Anime1"   ,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Sp_美剧星球","name":"美剧┃美剧星球","type":3,"api":"csp_Mjxq"     ,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Sp_直播合集","name":"直播┃网红直播","type":3,"api":"csp_Yj1211"   ,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Sp_三陆零官","name":"官方┃三陆零官" ,"type":3,"api":"csp_SP360"   ,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Sp_爱起艺官","name":"官方┃爱起艺官","type":3,"api":"csp_IQIYI"    ,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Sp_起鹅视频","name":"官方┃起鹅视频","type":3,"api":"csp_QQ"       ,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Sp_陆小果官","name":"官方┃陆小果官","type":3,"api":"csp_MGTV"     ,"searchable":1,"quickSearch":1,"filterable":1},
{"key": "牛马TV(DR)","name": "牛马TV[JS]","type": 3,"api": "https://notabug.org/qizhen15800/My9394/raw/master/jar/drpy.js","ext": "https://notabug.org/qizhen15800/My9394/raw/master/js/%e7%89%9b%e9%a9%acTV.js"},
{"key": "酷云77(DR)","name": "酷云77[JS]","type": 3,"api": "https://notabug.org/qizhen15800/My9394/raw/master/jar/drpy.js","ext": "https://notabug.org/qizhen15800/My9394/raw/master/js/%e9%85%b7%e4%ba%9177.js"},
{"key": "LIBVIO(DR)","name": "LIBVIO[JS]","type": 3,"api": "https://notabug.org/qizhen15800/My9394/raw/master/jar/drpy.js","ext": "https://notabug.org/qizhen15800/My9394/raw/master/js/LIBVIO.js"},
{"key": "555影视(DR)","name": "555影视[JS]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.js","ext": "https://notabug.org/qizhen15800/My9394/raw/master/js/555%e5%bd%b1%e8%a7%86.js"},
{"key": "追剧喵(DR)","name": "追剧喵[JS]","type": 3,"api": "https://notabug.org/qizhen15800/My9394/raw/master/jar/drpy.js","ext": "https://notabug.org/qizhen15800/My9394/raw/master/js/%e8%bf%bd%e5%89%a7%e5%96%b5.js"},
{"key": "玄天(DR)","name": "玄天[JS]","type": 3,"api": "https://notabug.org/qizhen15800/My9394/raw/master/jar/drpy.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/玄天.js"},
{"key": "AnFuns(DR)","name": "AnFuns[JS]","type": 3,"api": "https://notabug.org/qizhen15800/My9394/raw/master/jar/drpy.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/AnFuns.js"},
{"key": "大米星球(DR)","name": "大米星球[JS]","name": "acfun[JS]","type": 3,"api": "https://notabug.org/qizhen15800/My9394/raw/master/jar/drpy.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/大米星球.js"},
{"key": "莫扎兔(DR)","name": "莫扎兔[JS]","type": 3,"api": "https://notabug.org/qizhen15800/My9394/raw/master/jar/drpy.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/莫扎兔.js"},
{"key": "007影视(DR)","name": "007影视[JS]","type": 3,"api": "https://notabug.org/qizhen15800/My9394/raw/master/jar/drpy.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/007影视.js"},
{"key": "干饭影视(DR)","name": "干饭影视[JS]","type": 3,"api": "https://notabug.org/qizhen15800/My9394/raw/master/jar/drpy.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/干饭影视.js"},
{"key": "番茄影视(DR)","name": "番茄影视[JS]","type": 3,"api": "https://notabug.org/qizhen15800/My9394/raw/master/jar/drpy.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/番茄影视.js"},
{"key": "360影视(DR)","name": "360影视[JS]","type": 3,"api": "https://notabug.org/qizhen15800/My9394/raw/master/jar/drpy.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/360影视.js"},
{"key": "腾讯视频(DR)","name": "腾讯视频[JS]","type": 3,"api": "https://notabug.org/qizhen15800/My9394/raw/master/jar/drpy.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/腾云驾雾.js"},
{"key": "芒果TV(DR)","name": "芒果TV[JS]","type": 3,"api": "https://notabug.org/qizhen15800/My9394/raw/master/jar/drpy.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/百忙无果.js"},
{"key": "爱奇艺(DR)","name": "爱奇艺[JS]","type": 3,"api": "https://notabug.org/qizhen15800/My9394/raw/master/jar/drpy.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/奇珍异兽.js"},
{"key": "优酷(DR)","name": "优酷[JS]","type": 3,"api": "https://notabug.org/qizhen15800/My9394/raw/master/jar/drpy.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/优酷.js"},
{"key": "搜狗(DR)","name": "搜狗[JS]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/菜狗.js"},
{"key": "鸭奈飞(DR)","name": "鸭奈飞[JS]","type": 3,"api": "https://notabug.org/qizhen15800/My9394/raw/master/jar/drpy.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/鸭奈飞.js"},
{"key": "蓝光影院(DR)","name": "蓝光影院[JS]","type": 3,"api": "https://notabug.org/qizhen15800/My9394/raw/master/jar/drpy.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/蓝光影院.js"},
{"key": "万能影视(DR)","name": "万能影视[JS]","type": 3,"api": "https://notabug.org/qizhen15800/My9394/raw/master/jar/drpy.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/万能影视.js"}
],
"spider":"https://gitee.com/qizhen169xt/cool_white/raw/master/videos-tool/jar/不良帅.txt;md5;a31253a7f79b34d1f62176740a1f9954",
"lives": [{"group": "redirect","channels": [{"name": "redirect","urls": ["proxy://do=live&type=txt&ext=aHR0cHM6Ly9hZ2l0LmFpL3FpMTY5L015OTM5NC9yYXcvYnJhbmNoL21hc3Rlci9UVi9saXZlLnR4dA=="]}]}],
"rules" : [{"host" : "*","rule" : ["douyinvod.com","/video/tos/cn/"]},{"host" : "*","rule" : ["default.365yg.com","/video/tos/cn/"]},{"host" : "*","rule" : ["/m3u8.php","path="]},{"host" : "zjmiao.com","rule" : ["play.videomiao.vip/API.php","time=","key=","path="]}],
"parses":[
{"name":"解析聚合","type":3,"url":"Demo"},
{"name":"Json并发","type":2,"url":"Parallel"},
{"name":"Json轮询","type":2,"url":"Sequence"},
{"name":"江湖小虾米","type":0,"url":"https://dm.xmflv.com:4433/?url="},
{"name":"yemu","url": "https://www.yemu.xyz/?url="},
{"name":"dbapp","url": "https://dbapp.hengj.cn/rr/tg/?url="},
{"name": "8old","type": 0,"url": "http://danmu.8old.cn/vip/?url=","ext": {"flag": ["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"free","type":0,"url":"https://h5.freejson.xyz/player/?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"],"header":{"User-Agent":"okhttp/4.1.0"}}},
{"name":"ceshi","type":1,"url":"http://211.99.99.236:4567/jhjson/ceshi.php?url=","ext":{"flag":["qiyi","iqiyi","奇艺","爱奇艺","qq","腾讯","youku","优酷","pptv","PPTV","letv","乐视","bilibili","哔哩哔哩","哔哩","mgtv","芒果","xigua","西瓜","sohu","搜狐","cntv","cctv","央视","1905","m1905"]}},
{"name":"gotka","type":1,"url":"http://newjiexi.gotka.top/keyu3.php?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"],"header":{"User-Agent":"okhttp/4.1.0"}}},
{"name":"hfys","type":1,"url":"http://119.91.206.244:9999/jx/hfys.php?url=","ext": {"flag": ["duoduozy", "renrenmi","ltnb","miaoparty","miaoparty2","miaoparty3","laodiyun","laodim3u8","lekanzyw","rx","CL4K","fuckapp","1080P", "wuduzy"]}},
{"name": "dygfsdy","type": 1,"url": "http://jx.dygfsdy.com/home/api?type=ys&uid=129415&key=acdmoruwxCDEKPZ679&url=","ext": {"flag": ["qq","腾讯","letv","乐视","mgtv","芒果","youku","优酷","qiyi","iqiyi","爱奇艺","奇艺"]}},
{"name": "anal23","type": 1,"url": "http://39.96.174.234:4433/analysis.php?app=10000&account=SVIP666&password=18123344653&url=","ext": {"flag": ["qiyi","qq","letv","sohu","youku","mgtv","bilibili","wasu","xigua","1905"]}},
{"name": "analysis", "type": 0,"url": "http://42.193.18.62:9999/analysis.php?v=","ext": { "flag": ["qq","腾讯", "qiyi", "爱奇艺","奇艺", "youku", "优酷","mgtv","芒果","letv","乐视","pptv", "PPTV", "sohu","bilibili","哔哩哔哩", "哔哩"]}},          
{"name": "wuyou","type": 0,"url": "http://wuyou.ueuo.com/jx.html?url=","ext": {"flag": ["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果"]}},
{"name":"七小时","url":"https://jxxxx.sanmitt.cn/index.php?url="},
{"name":"legen","url": "https://json.legendwhb.cn//llq//?url="},
{"name":"ckplayer","type":0,"url":"https://www.ckplayer.vip/jiexi/?url="},
{"name": "parwix","type": 0,"url": "https://vip.parwix.com:4433/player/?url=","ext": {"flag": ["ltnb","renrenmi","qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","bilibili","哔哩哔哩","哔哩"]}},
{"name":"17yun","url":"http://www.1717yun.com/api/?url="},
{"name":"扶风","type":1,"url":"https://vip.byteamone.cn/api/?key=iYOnljzBM3qy5y9qZ4&url="},
{"name":"ckmov","url":"https://www.ckmov.vip/api.php?url="},
{"name":"m3u8","url":"https://www.playm3u8.cn/jiexi.php?url="},
{"name":"07u8","url":"https://m3u8.07vod.cn/?url="},
{"name":"17ty","url":"http://www.1717yun.com/jx/ty.php?url="},
{"name":"M117","type":0,"url":"http://1.117.152.239:39000/?url="},
{"name":"M3U8解析","type":0,"url":"https://www.m3u8.tv.cdn.8old.cn/jx.php?url="},
{"name":"bozrc稳定","type":0,"url":"https://jx.bozrc.com:4433/player/?url="},
{"name":"ax","url": "https://api.ax.jx.cn/?url="},
{"name":"zui","type":0,"url":"https://jx.zui.cm/?url=","ext":{"flag":["ltnb"]}},
{"name":"8090","url":"https://www.8090g.cn/?url="},
{"name":"m3u8tv","url": "http://jx.m3u8.tv/jiexi/?url="},
{"name":"ecsxs","url":"https://wds.ecsxs.com/225173.html?url="},
{"name":"365","url":"https://jx.fulitang365.com/?url="},
{"name":"ltnb","type":0,"url":"https://jx.zui.cm/?url=","ext":{"flag":["ltnb"]}},
{"name":"ml1080","url": "https://www.ml1080.com//mg//?url="},  
{"name":"佳宸","type":0,"url":"http://1link.atwebpages.com/?url="},
{"name":"bl","type":0,"url":"https://svip.bljiex.cc/?v="},
{"name": "rongxing","type": 1,"url": "http://jx.dygfsdy.com/home/api?type=ys&uid=129415&key=acdmoruwxCDEKPZ679&url="},
{"name": "rx","type":1,"url": "https://rx.bt5v.com/json/jsonindex.php/?url="},
{"name": "rxvip","type": 1,"url": "https://vip.rongxingvr.top/api/?key=CwQXkIXGfaUNGVomez&url=","ext": {"flag": ["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name": "GGTV你啊","type":1,"url": "https://play.fuqizhishi.com/jx/API.php?appkey=xiaobaiiii&url="},
{"name":"ckplayer","type":0,"url":"https://www.ckplayer.vip/jiexi/?url="},
{"name": "kuanjv","type": 1,"url": "http://rxjx.kuanjv.com/allm3u8.php?url=","ext": {"flag": ["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","搜狐","sohu","letv","乐视","bilibili","哔哩哔哩","哔哩","xigua","西瓜"]}},
//{"name": "GGTV搜集","type": 1,"url": "https://play.fuqizhishi.com/juhe/API.php?appkey=caijijuhe220902&url="},
{"name":"托乌","type":0,"url":"https://jx.ppjbk.cn/?url="},
{"name":"icu","type":1,"url":"https://cache.json.icu/home/api?type=ys&uid=1362243&key=acfgklqwFLMORSTVZ6&url=","ext":{"flag":["qq","qiyi","mgtv","youku","letv","sohu","xigua","1905","bilibili","ltnb","renrenmi"]}},
{"name":"kumyun","type":1,"url":"http://www.kumyun.cn/home/api?type=ys&uid=12970&key=eopDJKLMNPSTVXY015&url="},
{"name":"优众","type":1,"url":"http://svip.nfjx.xyz/api/?key=wbbgCgezulNGcZVHc1&url="},
{"name": "无名","type": 1,"url": "https://www.administratorw.com/video.php?url="},
{"name": "爱豆解析","type": 0,"url": "https://jx.aidouer.net/?url="},
{"name":"快速","type":1,"url":"https://play.fuqizhishi.com/juhe/API.php?appkey=caijijuhe&url="},
{"name": "融xing","type": 1,"url": "https://vip.rongxingvr.top/api/?key=DIcBZqAMbKBa1fRdeM&url=","ext": {"flag": ["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name": "rongxing","type": 1,"url": "https://svip.rongxingvr.top/api/?key=bpWXKrAJUKm3puOCH4&url="},
{"name":"油果","type":1,"url":"http://json.youguo520.top/fufeng/?url=","ext":{"flag":["qiyi","爱奇艺","奇艺","qq","腾讯","youku","优酷","pptv","PPTV","letv","乐视","bilibili","哔哩哔哩","哔哩","mgtv","芒果"],"header":{"User-Agent":"Dart/2.14 (dart:io)"}}}, 
{"name": "beiyan","type": 1,"url": "https://jx.beiyan.cc:4433/?url=","ext": {"flag": ["youku","优酷","mgtv","芒果","qq","腾讯","qiyi","爱奇艺","qq","奇艺"]}},
{"name": "冰豆解析","type": 0,"url": "https://bd.jx.cn/?url="}
],
"flags":["youku","qq","iqiyi","imgo","xueren","m1905","qiyi","letv","sohu","tudou","pptv","dbm3u8","mgtv","wasu","bilibili","le","duoduozy","renrenmi","xigua","优酷","西瓜","乐视","芒果","腾讯","爱奇艺","奇艺","ltnb","rx","CL4K","xfyun","wuduzy","哔哩哔哩","哔哩"],
"ijk":[
{"group":"硬解码","options":[
{"category":4,"name":"opensles","value":"0"},
{"category":4,"name":"overlay-format","value":"842225234"},
{"category":4,"name":"framedrop","value":"1"},
{"category":4,"name":"soundtouch","value":"1"},
{"category":4,"name":"start-on-prepared","value":"1"},
{"category":1,"name":"http-detect-range-support","value":"0"},
{"category":1,"name":"fflags","value":"fastseek"},
{"category":2,"name":"skip_loop_filter","value":"48"},
{"category":4,"name":"reconnect","value":"1"},
{"category":4,"name":"enable-accurate-seek","value":"0"},
{"category":4,"name":"mediacodec","value":"1"},
{"category":4,"name":"mediacodec-auto-rotate","value":"1"},
{"category":4,"name":"mediacodec-handle-resolution-change","value":"1"},
{"category":4,"name":"mediacodec-hevc","value":"1"},
{"category":1,"name":"dns_cache_timeout","value":"600000000"}
]},
{"group":"软解码","options":[
{"category":4,"name":"opensles","value":"0"},
{"category":4,"name":"overlay-format","value":"842225234"},
{"category":4,"name":"framedrop","value":"1"},
{"category":4,"name":"soundtouch","value":"1"},
{"category":4,"name":"start-on-prepared","value":"1"},
{"category":1,"name":"http-detect-range-support","value":"0"},
{"category":1,"name":"fflags","value":"fastseek"},
{"category":2,"name":"skip_loop_filter","value":"48"},
{"category":4,"name":"reconnect","value":"1"},
{"category":4,"name":"enable-accurate-seek","value":"0"},
{"category":4,"name":"mediacodec","value":"0"},
{"category":4,"name":"mediacodec-auto-rotate","value":"0"},
{"category":4,"name":"mediacodec-handle-resolution-change","value":"0"},
{"category":4,"name":"mediacodec-hevc","value":"0"},
{"category":1,"name":"dns_cache_timeout","value":"600000000"}
]}
],
//"wallpaper": "http://www.kf666888.cn/api/tvbox/img",
"wallpaper":"http://52bsj.vip:82/late",  
"ads":["mimg.0c1q0l.cn","www.googletagmanager.com","www.google-analytics.com","mc.usihnbcq.cn","www.stappupgrade.vivo.com.cn","mg.g1mm3d.cn","www.otheve.beacon.qq.com","mscs.svaeuzh.cn","cnzz.hhttm.top","tp.vinuxhome.com","cnzz.mmstat.com","www.baihuillq.com","s23.cnzz.com","z3.cnzz.com","c.cnzz.com","stj.v1vo.top","z12.cnzz.com","img.mosflower.cn","tips.gamevvip.com","ehwe.yhdtns.com","xdn.cqqc3.com","www.jixunkyy.cn","sp.chemacid.cn","hm.baidu.com","s9.cnzz.com","z6.cnzz.com","um.cavuc.com","mav.mavuz.com","wofwk.aoidf3.com","z5.cnzz.com","xc.hubeijieshikj.cn","tj.tianwenhu.com","xg.gars57.cn","k.jinxiuzhilv.com","cdn.bootcss.com","ppl.xunzhuo123.com","xomk.jiangjunmh.top","img.xunzhuo123.com","z1.cnzz.com","s13.cnzz.com","xg.huataisangao.cn","z7.cnzz.com","xg.huataisangao.cn","z2.cnzz.com","s96.cnzz.com","q11.cnzz.com","thy.dacedsfa.cn","xg.whsbpw.cn","s19.cnzz.com","z8.cnzz.com","s4.cnzz.com","f5w.as12df.top","ae01.alicdn.com","www.92424.cn","k.wudejia.com","vivovip.mmszxc.top","qiu.xixiqiu.com","cdnjs.hnfenxun.com","cms.qdwght.com"]}


